pipeline:
  # restore the cache from an sftp server
  restore_cache:
    image: appleboy/drone-sftp-cache
    restore: true
    mount: [ .glide, vendor ]
    ignore_branch: true

  build:
    image: appleboy/golang-testing
    pull: true
    environment:
      - GOPATH=/go
    commands:
      - glide install
      - coverage all

  notify:
    image: plugins/slack
    channel: jenkins
    username: drone
    when:
      status: [ success, failure ]
    template: |
      *{{ build.status }}* <{{ build.link }}|{{ repo.owner }}/{{ repo.name }}#{{ truncate build.commit 8 }}> ({{ build.branch }}) by {{ build.author }}.
    image_url: https://cdn3.iconfinder.com/data/icons/picons-social/57/16-apple-128.png

  slack:
    image: plugins/slack
    channel: drone
    username: drone
    when:
      status: [ killed, success, failure ]
    template: |
      *{{ build.status }}* <{{ build.link }}|{{ repo.owner }}/{{ repo.name }}#{{ truncate build.commit 8 }}> ({{ build.branch }}) by {{ build.author }}.
    icon_url: https://cdn3.iconfinder.com/data/icons/picons-social/57/16-apple-128.png

  line:
    image: appleboy/drone-line
    pull: true
    to: u359650f919427b5229330c7205c47ee4

  facebook:
    image: appleboy/drone-facebook
    pull: true
    to: 1234973386524610

  # rebuild the cache on the sftp server
  rebuild_cache:
    image: appleboy/drone-sftp-cache
    rebuild: true
    mount: [ .glide, vendor ]
    ignore_branch: true
    when:
      branch: master

workspace:
  path: /go/src/github.com/appleboy/go-hello
