FROM alpine

MAINTAINER Bo-Yi Wu <appleboy.tw@gmail.com>

RUN apk update && apk upgrade \
  && apk add ca-certificates \
  && rm -rf /var/cache/apk/*

RUN mkdir /app
ADD build.tar.gz /app/
ENTRYPOINT /app/hello-world
EXPOSE 8000
