FROM appleboy/golang-testing

MAINTAINER Bo-Yi Wu <appleboy.tw@gmail.com>

ENV app /go/src/github.com/appleboy/go-hello

RUN mkdir -p $app
ADD . $app
WORKDIR $app
RUN make install
RUN go build -ldflags="-s -w" hello-world.go
CMD tar -czf - hello-world
